name: 'TODO'
description: 'TODO'
branding:
  icon: at-sign
  color: blue

inputs:
  github-token:
    description: "The github token"
  working-directory:
    description: "The path in which semantic-release should run"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependecies
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      shell: sh
    
    - name: Next version
      working-directory: ${{ inputs.working-directory }}
      run: |
        cp ${GITHUB_ACTION_PATH}/pre-release.config.js .
        baseConfigFile=./release.config.js npx semantic-release --extends=./pre-release.config.js --dry-run --no-ci
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: sh
