name: Build and Deploy

on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
